changelog:
  categories:
    - title: 🚀 New Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
  replacers:
    - search: ".*"
      replace: "$0"
